### ISSUE TITLE
URLs to deb files are no longer valid

### ISSUE THREAD

**Issue by ShawnZhong** [xrp-project/XRP#2]
It seems that the following links to the .deb files are no longer valid:

https://github.com/xrp-project/XRP/blob/6912ef6525681fb1b557cb2d6619c97cd830a71a/build_and_install_bpfkv.sh#L15-L17

I'd suggest replacing them with the following from old-releases.ubuntu.com:

https://old-releases.ubuntu.com/ubuntu/pool/universe/libb/libbpf/libbpf0_0.1.0-1_amd64.deb
https://old-releases.ubuntu.com/ubuntu/pool/universe/libb/libbpf/libbpf-dev_0.1.0-1_amd64.deb
https://old-releases.ubuntu.com/ubuntu/pool/universe/d/dwarves-dfsg/dwarves_1.17-1_amd64.deb

**Comment by yuhong-zhong** [comment]
Thanks for spotting this issue and suggesting the fix! The links were updated.
